name: local-gateway

services:
  traefik:
    image: traefik:v3.7.8
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=local-gateway
      - --entrypoints.web.address=:80
    ports:
      - "127.0.0.1:80:80"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - local-gateway

networks:
  local-gateway:
    name: local-gateway
